wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714385352.798057
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 1
      - 23
      4: 3.9.16
      5: 0.16.3
      6: 4.39.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
